name: 'devcontainer CI' 
on:
  workflow_dispatch:
  pull_request:
    branches:
      - 2425-devel
  push:
    branches:
      - 2425-devel

jobs:
  build:
    runs-on: lcas
    steps:
      - name: Node Js
        uses: actions/setup-node@v4
        with:
          node-version: "^16.13.0 || >=18.0.0"
      - name: Checkout (GitHub)
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: 'recursive'
      - name: What
        run: echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - name: Build container
        uses: devcontainers/ci@v0.3
        with:
          imageName: lcas.lincoln.ac.uk/devcontainer/ros2-teaching
          push: never
          imageTag: ci
          #runCmd: "bash .devcontainer/run-ci.sh"
