name: 'devcontainer CI' 
on:
  workflow_dispatch:
  pull_request:
    branches:
      - 2425-devel
  push:
    branches:
      - 2425-devel

jobs:
  build:
    runs-on: lcas
    steps:
      - name: Node Js
        uses: actions/setup-node@v4
        with:
          node-version: "^16.13.0 || >=18.0.0"
      - name: Checkout (GitHub)
        uses: actions/checkout@v4
      - name: What
        run: echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - name: Build container
        if: ${{ github.event_name != 'pull_request' }} 
        uses: devcontainers/ci@v0.3
        with:
          imageName: devcontainer/ros2-teaching
          push: never
          imageTag: ${{ env.BRANCH }}
          #runCmd: "bash .devcontainer/run-ci.sh"
